name: CI/CD Workflow with Railway

on:
  push:
    branches:
      - "main"
      - "staging"
  workflow_dispatch: # Allows manual deployment trigger

jobs:
  lint-and-test:
    name: Linting and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Linting
        run: mvn checkstyle:check

      - name: Run Tests
        run: mvn test

  deploy:
    name: Manual Deployment to Railway
    runs-on: ubuntu-latest
    needs: lint-and-test # Ensures linting and tests pass before deployment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          railway login --token $RAILWAY_TOKEN
          railway up --projectId ${{ secrets.RAILWAY_PROJECT_ID }} --environment ${{ github.ref_name == 'main' && 'production' || 'staging' }}

      - name: Confirm Deployment
        run: echo "Deployment to Railway for ${{ github.ref_name }} branch completed!"
