name: CI/CD Workflow with Railway

on:
  push:
    branches:
      - "main"
      - "staging"
  workflow_dispatch: # Allows manual deployment trigger

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Linting
        run: mvn spotless:check

  test:
    name: Test (Echo Only)
    runs-on: ubuntu-latest
    needs: lint # Ensures linting passes before tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Echo Test Placeholder
        run: echo "Tests are skipped for now."

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up